### ISSUE TITLE
Support for multiple API endpoints

### ISSUE THREAD

**Issue by kmaris** [directus/docker#11]
Is there any work being done for supporting multiple API's? I see a placeholder: https://github.com/directus/docker/tree/master/examples/multiple-api

I could do some work towards this, I have a demo for another issue directus/api#636 that might have a useful docker-compose.yml to get things rolling: https://github.com/kmaris/directus-demo

**Comment by WoLfulus** [comment]
Hi @kmaris !

The placeholder will be just an example that spawns multiple different containers for different api instances. Nothing related to multiple api.php files.

Mouting the config like you did works just fine, but we're focusing on getting instances configured through environment variables, and having different apis on the same containers makes it hard to get it right, if not impossible.

**Comment by kmaris** [comment]
The directus-demo was more about showing an issue with hosting under a path that's not /, something like /catalogue. Multiple api containers would be fine. Same with multiple database containers.

The problem I am running into is urls. Seems the api and app are using urls like /interfaces, /collections, etc which are global to the api instance. For my hosting situation there's no chance of using urls like that nor can I use multiple domains for hosting (much to my chagrin). 

It seems like to have a project name (something not /_/) you also need the default project defined in api.php. Any tricks to this that I'm not aware of?

**Comment by WoLfulus** [comment]
I didn't get it. You want to host different apis on different paths? Like...

- API1 -> /api1/_/
- API2 -> /api2/_/

**Comment by narkowicz** [comment]
We'd like to be able to use [_Multitenancy_](https://docs.directus.io/guides/projects.html#multitenancy) instead of multiple containers if possible.

This is partly motivated by putting a ceiling on the number of containers (i.e. 1 rather than _n_) as we add projects - which in our case is a premature optimisation.

Mainly though, we'd like to have a single public subdomain on port 80 for all API end points, without mucking around too much with routing to each container. Will look at Traefik and @kmaris' demo :thumbsup: :thumbsup:

Would be great to have 1st party support for _Multitenancy_ but also not sure how this would be achieved _elegantly_ with environment variables - iterating over all similar optionally name-spaced env variables (i.e. `DATABASE_NAME_[PROJECT]` or `[PROJECT_]DATABASE_NAME` etc. - as per `API_ENDPOINT` in `app` container) and outputting multiple config files from a template? :confounded:

As an aside, we also happen to hold a _minor_ aversion to the convention of having a default project under the `/_/` path - would prefer all projects be named - but there's no requirement for the default project to have content or be referenced / selectable from the app :ok_hand:

**Comment by WoLfulus** [comment]
@narkowicz you'd still be able to mount your own api.php files to config folder (as a volume), in the current docker implementation you just need to unset (or set to 0) the `DIRECTUS_USE_ENV` environment variable in the container, and it will load files from disk.

**Comment by enzolupia** [comment]
> The directus-demo was more about showing an issue with hosting under a path that's not /, something like /catalogue. Multiple api containers would be fine. Same with multiple database containers.
> 
> The problem I am running into is urls. Seems the api and app are using urls like /interfaces, /collections, etc which are global to the api instance. For my hosting situation there's no chance of using urls like that nor can I use multiple domains for hosting (much to my chagrin).
> 
> It seems like to have a project name (something not /_/) you also need the default project defined in api.php. Any tricks to this that I'm not aware of?

Hi,
I'm facing the same issue, did you find any solution to the problem?
Currently I have multiple containers each hosting a specific project, for example /api/project1 get redirected to container1, /api/project2 gets redirected to container2, but I don't understand where all the requests to non-specific api path like /api/interfaces or /api/pages should be handled.

Any advice ?
