### ISSUE TITLE
Setup automated builds

### ISSUE THREAD

**Issue by inta** [directus/docker#33]
I'm starting to use/learn Directus and Docker for the project setup. I recognised the *.0.19 release is missing on Docker hub and yesterdays release as well. Do you build the Docker images manually?

However, it would be great if the images are created automatically. As you (obviously) have access to the Github repos it should be possible to setup Dockers automated builds. Please consider doing that. :)

**Comment by benhaynes** [comment]
I believe this is either automated, or about to be automated. Right, @WoLfulus ?

There might be an issue because we changed our version naming convention for the combined build yesterday.

**Comment by WoLfulus** [comment]
We disabled the auto builds for the last few releases because we're refactoring the whole repository and how we build/manage the images. There were so many issues that we're changing the approach on how we deliver the builds. 

I'm trying to get things working properly before hitting the `auto` button again, but we'll get the docker releases going again ASAP and hopefully with more image flavours (nginx, apache, caddy...)
