### ISSUE TITLE
Unable to switch between projects with only one API and one APP

### ISSUE THREAD

**Issue by lluishi93** [directus/docker#50]
Hi @WoLfulus 

I'm having troubles creating a directus setup like this, using your single-api example as a base:
- A single app container with these environment variables:
  - An API_ENDPONT = Dev; http://localhost:7000/_/
  - An API_ENDPOINT_PROD = Prod; http://localhost:7000/prod/
- A single api container
- A single mysql container

Before starting the whole thing, I make sure to create the prod database first, so I've two databases for two projects in the same API (and I'm able to see the dropdown in the Admin UI), and a project called prod, using a /projects URL call with POST method, with the same credentials for both projects

But when I try to switch from the Dev option to Prod, I get redirected to the login form, and when I enter the email and password, I'm still pointing to the dev project in the UI.

Could you give me some ideas to figure out what am I doing wrong?

Thank you, and BR

**Comment by WoLfulus** [comment]
hi, sorry the delay!

since we do not have 1st class support for multitenancy in docker (which is what you're requesting), to accomplish this using containers, you'd need to have two of them running + a load balancer in order to do that

for example:

containers
- app 
- api1
- api2
- lb

lb routes
- api.domain.tld/_/ -> api1
- api.domain.tld/prod/ -> api2
- admin.domain.tld/ -> app
