### ISSUE TITLE
API is not returning a https url when getting file data.

### ISSUE THREAD

**Issue by rodrigosanabria17** [directus/docker#51]
When getting file data from the item service, instead of returning the full url with https, it only returns it with http.
 I'm not sure if I have to add some environment variable in api service definiton or it's something else, does somebody have any idea of how to fix it?

**Comment by benhaynes** [comment]
Hey @WoLfulus — is this Docker specific, or could it be an API issue?

**Comment by WoLfulus** [comment]
This can be both to be honest. If running behind a load balancer and it rewrites to http, webserver will detect as http, so we must have a config to always force https instead of auto detection in api core.

If this is the case I'd change this inside api not docker because any other setup that involves a reverse proxy will likely cause this

**Comment by benhaynes** [comment]
Thoughts on this @directus/admin ?

**Comment by benhaynes** [comment]
Thoughts on this @directus/api-team ?

**Comment by rijkvanzanten** [comment]
I believe the config might allow for absolute URLs for the root path for files too, which negates this problem

**Comment by WoLfulus** [comment]
@rodrigosanabria17 did you solve this? I ran into the same problem and I fixed it by forcing the https forward headers into nginx load balancer. So it's not related to out setup, but the how we configure the load balancers.

@rijkvanzanten I believe it would be nice to have a way to overwrite the auto detection of http/https and specify a base url for some specific cases. I spent a lot of time trying to fix that in my setup without touching directus itself.

I'm closing this for now, and I believe this should be in `api` instead of docker as its an environmental issue that can happen without having docker itself. Any load balancer not properly configured can make this happen.
