### ISSUE TITLE
Where are the images?

### ISSUE THREAD

**Issue by johannesfritsch** [directus/docker#54]
The last image I could find is for 2.0.18/7.0.18. Is the build broken?

**Comment by benhaynes** [comment]
@WoLfulus is working on this now and should have updated versions in the next day or so.

**Comment by johannesfritsch** [comment]
Hey, thanks for the fast reply!

**Comment by hakkurishian** [comment]
What is the best version to update to as of now?

My current docker-compose looks like this:


` #   
  # Directus
  #
  api:
    image: directus/api:latest
    volumes:
      - "./cms/extensions/custom:/var/www/html/public/extensions/custom"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: "directus"
      DATABASE_USERNAME: "directus"
      DATABASE_PASSWORD: "directus"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
      API_HOST: ${HOST}
    ports:
      - 7000:80

  #
  # Dashboard
  #
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://${HOST}:7000/_/"
      API_HOST: ${HOST}
    ports:
      - 8000:80
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password`

Using the "latest" tag I don't seem to get any later version of Directus than 7.0.18. When I pull"base-apache-0.0.8" instead, accessing the site just gives me 404 errors. I suspect this is because it is a base and no "dist" image. Are there up to date images already provided or is this still worked on @WoLfulus  ? :) Do I have to change any of the config related to that?

**Comment by johannesfritsch** [comment]
I think they are working on getting the build process up and running again. Right now the latest versions are 2.0.18/7.0.18. These images are half a year old. We are also waiting for newer images as we have strange behavior with datetimes where localtime is saved to the DB instead of an UTC.

**Comment by johannesfritsch** [comment]
Any news, @WoLfulus?

**Comment by aiomaster** [comment]
So can I just use my current docker-compose.yml and do `docker-compose pull` or to I have to take more steps to upgrade to the new images?

**Comment by WoLfulus** [comment]
`directus/api:v2.5.0-apache` and `directus/app:v7.10.0-node` has been pushed to docker hub for those willing to test it. 

it still needs to be documented, since it changed a little from the old version, but there's a simple example on `develop` branch

https://github.com/directus/docker/blob/develop/examples/simple.yaml 

note that there's still a workflow problem, and right now, the database needs to be populated by hand in order for it to work properly, but we're working on it
