### ISSUE TITLE
directus dev-environment with docker

### ISSUE THREAD

**Issue by webdeb** [directus/docker#55]
Hey @WoLfulus just wanted to ask quickly how would you setup an dev-environment with docker for directus itself? I want to play around with the pgsql branch, but since I am not a php developer (no apache, no php, no mysql locally), I would like to containerise the work on it.

**Comment by WoLfulus** [comment]
Right now you'd setup the containers yourself (I mean writing Dockerfiles and docker-compose.yml). We're still in the process of releasing the official images, which will ease this process quite a bit. I can't give much details right now because I'm changing a lot of stuff yet. 

But in resume, we'll probably deliver a Dockerfile with a docker-compose.yml on api and app projects when everything is done :)

I know this is not that helpful right now, but I hope you take a look after the release

**Comment by webdeb** [comment]
> But in resume, we'll probably deliver a Dockerfile with a docker-compose.yml on api and app projects when everything is done :)
> I know this is not that helpful right now, but I hope you take a look after the release

This sounds good. Thank you!
