### ISSUE TITLE
Docker "Cannot serve directory /var/www/html/"

### ISSUE THREAD

**Issue by mukowman** [directus/docker#86]
Trying out the new directus/directus docker image I was able to get the installtion and database setup completed but now receive the following error message when running the docker container. FYI I am not using docker-compose just docker with a separate mysql image.

> Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive

Any ideas on which way to go?

**Comment by eulervoid** [comment]
I'm getting a similar problem via docker-compose. The installation runs fine, but then there is nothing found at `/` or `/admin`. Apache seems to serve an empty `/var/www/html`. Is there maybe a step that should link `/var/directus/public` to `/var/www/html` that is not being performed?
Could it be because `docker-compose run` is run in a new docker container instead of the one being created by the `docker-compose up -d`

**Comment by WoLfulus** [comment]
The current image is broken. I'm about to push a fix for this.

**Comment by WoLfulus** [comment]
Should be fixed in 
https://github.com/directus/docker/releases/tag/v8.3.1%2Bdocker.1

Just pull your image again and let me know if there are any issues with it
